apiVersion: v1
kind: Service
metadata:
  name: sentinel-arlo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: arlo
    context: sentinel
    version: v1
